### ISSUE TITLE
One proxy container = One UserAgent 

### ISSUE THREAD

**Issue by wheelspace** [bekh6ex/firefox-container-proxy#27] opened 2020-09-09 23:09 UTC

**Comment by nobodysu** [comment] 2020-09-10 09:14
Is there really a necessity? UA substitution only reliable without JS on modern browsers, otherwise it's a snake oil which makes you stand out:
https://whoer.net (Ctrl + F, Headers)
Moreover, UA could not be changed via extension when `privacy.resistFingerprinting` is enabled.

**Comment by wheelspace** [comment] 2020-09-11 11:28
![proxy](https://user-images.githubusercontent.com/61442625/92920449-f4c43000-f43a-11ea-92b6-cdf24ee2b980.png)
![permissions](https://user-images.githubusercontent.com/61442625/92920450-f4c43000-f43a-11ea-9791-37af69feba27.png)
![Screenshot_20200911_123819](https://user-images.githubusercontent.com/61442625/92920462-f857b700-f43a-11ea-94f9-78875d7dc297.png)

**Comment by nobodysu** [comment] 2020-09-12 14:42
So they found the workaround - that's good.
But what about all these individual [Navigator Object](https://browserleaks.com/javascript) values, are they also spoofed? And [JA3 SSL](https://ja3er.com/)?

**Comment by wheelspace** [comment] 2020-09-13 13:38
No. This can be done?

**Comment by nobodysu** [comment] 2020-09-13 15:45
Nothing that I aware of. I think these values are hardcoded, at least for now.

**Comment by xaiki** [comment] 2020-10-10 08:31
duplicate of #14

**Closed** 2021-11-04 19:54 UTC
